# Site settings
title: AviFish
titleExtended: Avidyne Babel Fish
subtitle: The happy translator for Perforce Web Query
email: dgallagher@avidyne.com
description: > # this means to ignore newlines until "baseurl:"
  This application is created to generate links by reaching out to a Perforce Web server
  grabbing the files from a specified changelist and printing out the result as a list so 
  links can be created to all the files on that changelist at that changelist version of the file.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.slylion.com/AviFish" # the base hostname & protocol for your site
copyright: "&copy; Dan Gallagher 2015"

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"